### PR TITLE
Reject failed queries

### PR DESCRIPTION
**Pull request by srounce**
Queries that were unable to return a value were previously `resolve`d, making handling code tricky to deal with (checking for resolved value every time). This PR replaces these calls with `reject`ion to a `null` value.

### CODE REVIEW

**Comment by ianlin** [comment]
Hey @srounce thanks!

What about I rebase my master first and you submit a new PR?

Hopefully @anarchicknight will reply @anarchicknight/react-native-carrier-info#2 soon!

**Comment by srounce** [comment]
> What about I rebase my master first and you submit a new PR?

Sure thing dude. Lemme know when you get round to it.

**Comment by ianlin** [comment]
Ah didn't notice this PR has the original commits included, merge it anyway, cheers!

**Comment by anarchicknight** [comment]
I am more than happy to transfer the original repo over to anyone who wants to maintain it, just let me know within and npm details and I can sort it in the next few days

**Pull request merged**
